// frontend/src/app/Components/NavBar/nav-bar-not-log-in/nav-bar-not-log-in.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'nav-bar-not-log-in',
  templateUrl: './nav-bar-not-log-in.component.html',
  styleUrls: ['./nav-bar-not-log-in.component.css']
})
export class NavBarNotLogInComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<ul class="navbar-nav d-flex">
    <li class="nav-item"><a routerLink="/login" class="nav-link">会員ログイン</a></li>
    <li class="nav-item"><a routerLink="/register" class="nav-link">新規登録</a></li>
    <li class="nav-item"><a routerLink="/login_admin" class="nav-link">管理者ログイン</a></li>
</ul>

// frontend/src/src/components/navbar/NavBarNotLogIn.vue
<template>
    <ul class="navbar-nav d-flex">
        <li class="nav-item"><router-link to="/login"><span class="nav-link">会員ログイン</span></router-link></li>
        <li class="nav-item"><router-link to="/register"><span class="nav-link">新規登録</span></router-link></li>
        <li class="nav-item"><router-link to="/login_admin"><span class="nav-link">管理者ログイン</span></router-link></li>
    </ul>
</template>

<script>
export default {
    name: "NavBarNotLogin"
}
</script>
