// frontend/src/app/Components/NavBar/nav-bar-admin/nav-bar-admin.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LogInService } from 'src/app/Services/log-in.service';
import conn from '../../../Modules/apiconnection';

@Component({
  selector: 'nav-bar-admin',
  templateUrl: './nav-bar-admin.component.html',
  styleUrls: ['./nav-bar-admin.component.css']
})
export class NavBarAdminComponent implements OnInit {

  constructor(private logInService: LogInService, private router: Router) { }

  ngOnInit(): void {
  }

  async logout(): Promise<void> {
    if (!confirm("ログアウトしますか？")) { return; }

    await conn.get("/admin/logout");
    this.logInService.LogOut();
    this.router.navigate(["/"]);
  }

}

<div class="navbar-nav">
    <span class="nav-item nav-link" on-click="logout()">ログアウト</span>
</div>

// frontend/src/src/components/navbar/NavBarAdmin.vue
<template>
    <div class="navbar-nav">
        <span class="nav-item nav-link" @click="logout">ログアウト</span>
    </div>
</template>

<script>
import { get } from '../../modules/APIConnection';

export default {
    name: "NavBarAdmin",
    methods: {
        logout: async function () {
            if (!confirm("ログアウトしますか？")) { return; }
            const res = await get("/admin/logout");
            if (res.status != 200) {
                alert("ログアウトに失敗しました");
                return;
            }
            this.$store.commit("logout");
            this.$router.push("/");
        }
    }
}
</script>

<style scoped>
span .nav-link {
    cursor: pointer;
}
</style>
