// frontend/src/app/Components/NavBar/nav-bar-user/nav-bar-user.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LogInService } from 'src/app/Services/log-in.service';
import conn from '../../../Modules/apiconnection';

@Component({
  selector: 'nav-bar-user',
  templateUrl: './nav-bar-user.component.html',
  styleUrls: ['./nav-bar-user.component.css']
})
export class NavBarUserComponent implements OnInit {

  constructor(public logInService: LogInService, private router: Router) { }

  ngOnInit(): void {
  }

  async logout(): Promise<void> {
      if (!confirm("ログアウトしますか？")){ return; }
      await conn.get("/user/logout");
      this.logInService.logOut();
      this.router.navigate(["/"]);
  }
}

<div class="navbar-nav">
    <span class="ml-5">
        <span class="nav-item nav-link">{{ logInService.getUserName() }} 様</span>
    </span>
    <a routerLink="/cart" class="nav-item nav-link">カートへ</a>
    <a routerLink="/history" class="nav-item nav-link">購入履歴</a>
    <a routerLink="/update" class="nav-item nav-link">ユーザ情報更新</a>
    <span class="nav-item nav-link logout" on-click="logout()">ログアウト</span>
</div>

// frontend/src/src/components/navbar/NavBarUser.vue
<template>
    <div class="navbar-nav">
        <span class="ml-5">
            <span class="nav-item nav-link">{{ $store.getters.name }} 様</span>
        </span>
        <router-link to="/user/cart"><span class="nav-item nav-link">カートへ</span></router-link>
        <router-link to="/user/history"><span class="nav-item nav-link">購入履歴</span></router-link>
        <span class="nav-item nav-link" @click="logout">ログアウト</span>
    </div>
</template>

<script>
import { get } from '../../modules/APIConnection';

export default {
    name: "NavBarUser",
    methods: {
        logout: async function () {
            if (!confirm("ログアウトしますか？")) { return; }
            const res = await get("/user/logout");
            if (res.status != 200) {
                alert("ログアウトに失敗しました");
                return;
            }
            this.$store.commit("logout");
            this.$router.push("/");
        }
    }
}
</script>

<style scoped>
span .nav-link {
    cursor: pointer;
}
</style>
