// frontend/src/src/components/navbar/NavBar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <router-link to="/"><span class="navbar-brand">通販システム</span></router-link>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                </ul>
                <span v-if="!$store.getters.isLogin">
                    <nav-bar-not-login />
                </span>
                <span v-else>
                    <span v-if="$store.getters.isUser">
                        <nav-bar-user />
                    </span>
                    <span v-else>
                        <nav-bar-admin />
                    </span>
                </span>
            </div>
        </div>
    </nav>
</template>

<script>
import NavBarAdmin from './NavBarAdmin.vue';
import NavBarNotLogin from './NavBarNotLogIn';
import NavBarUser from './NavBarUser.vue';

export default {
    name: "NavBar",
    components: {
        NavBarNotLogin,
        NavBarAdmin,
        NavBarUser
    }
}
</script>

<style scoped>
</style>

// frontend/src/app/Views/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { LogInService } from 'src/app/Services/log-in.service';

@Component({
  selector: 'nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {

  constructor(public logInService: LogInService) { }

  ngOnInit(): void {
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a routerLink="/"><span class="navbar-brand">通販システム</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <span *ngIf="!logInService.IsLogIn()">
                未ログイン
            </span>
            <span *ngElse>
                <span *ngIf="logInService.IsUser()">
                    ユーザ
                </span>
                <span *ngElse>
                    管理者
                </span>
            </span>
    </div>
    </div>
</nav>
