// frontend/src/app/Views/add-product/add-product.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import conn from '../../Modules/apiconnection';

@Component({
  selector: 'add-product',
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent implements OnInit {

  name: string
  price: number
  imageUrl: string
  description: string

  constructor(private router: Router) {
    this.name = "";
    this.price = 0;
    this.imageUrl = "";
    this.description = "";
  }

  ngOnInit(): void {
  }

  async submit(): Promise<void> {
    if (!confirm("追加しますか？")) { return; }
    
    var params = new URLSearchParams();
    params.append("name", this.name);
    params.append("price", this.price.toString()!);
    params.append("imageUrl", this.imageUrl);
    params.append("description", this.description);

    const res = await conn.post("/admin/product/add", params);
    if (res.status != 200 || !res.json.result) {
      alert("追加に失敗しました。");
      return;
    }

    alert("追加しました。");
    this.router.navigate(["/admin_top"]);
  }

}

<h1>商品追加</h1>
<hr />
<form (submit)="submit()">    
    <label class="form-label">商品名</label>
    <input type="text" class="form-control" name="name" [(ngModel)]="name" />
    <label class="form-label">値段</label>
    <input type="number" class="form-control" name="price" [(ngModel)]="price" />
    <label class="form-label">画像URL</label>
    <input type="text" class="form-control" name="imageUrl" [(ngModel)]="imageUrl" />
    <label class="form-label">商品概要</label>
    <textarea class="form-control" name="description" [(ngModel)]="description"></textarea>
    <input type="submit" class="btn btn-primary" value="追加" />
</form>

// frontend/src/src/views/AddProduct.vue
<template>
    <div>
        <h1>商品追加</h1>
        <hr />
        <label class="form-label">商品名</label>
        <input type="text" class="form-control" v-model="name" />
        <label class="form-label">値段</label>
        <input type="number" class="form-control" v-model="price" />
        <label class="form-label">画像URL</label>
        <input type="text" class="form-control" v-model="imageUrl" />
        <label class="form-label">商品概要</label>
        <textarea class="form-control" v-model="description"></textarea>
        <button class="btn btn-primary" @click="add">追加</button>
    </div>
</template>

<script>
import { post } from '../modules/APIConnection';

export default {
    name: "AddProduct",
    data: function () {
        return {
            name: "",
            price: 0,
            imageUrl: "",
            description: "",
        };
    },
    methods: {
        add: async function () {
            if (!confirm("追加しますか？")) { return; }

            var params = new URLSearchParams();
            params.append("name", this.name);
            params.append("price", this.price);
            params.append("imageUrl", this.imageUrl);
            params.append("description", this.description);
            const res = await post("/admin/product/add", params);
            if (res.status != 200) {
                alert("追加に失敗しました");
                return;
            }

            if (!res.json.result) {
                alert(res.json.errorMessage);
                return;
            }

            alert("追加しました");
            this.$router.push("/admin");
        }
    }
}
</script>
